version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
      exclude: _test\.go

formatters:
  enable:
    - gofmt
    - goimports
